### ISSUE TITLE
Transposed arrays

### ISSUE THREAD

**Issue by suessspeise** [ylikx/forpy#31]
When I create an array in Python, then pass it to Fortran as a return value, it is transposed in the process. This does not happen with arrays created in Fortran and then handed over to Python. Seemingly Forpy converts arrays properly and this particular use case might have been overseen.

This is how i created the array in Python
```python
[...]
  nrow = random.randint(1,6)
  ncol = random.randint(1,6)
  array = np.random.rand(ncol,nrow).transpose()
  optional_array = {"ncols":ncol, "nrows": nrow, "data":array}
  kwargs["optional_array"] = optional_array
return kwargs
```

**Comment by ylikx** [comment]
Forpy does not automatically convert the buffer underlying a numpy array to Fortran storage order, since this would involve creating a new array and have the cost of copying the whole buffer.

If you want to check which order a `ndarray` has, you can use `ndarray%is_ordered`:
https://github.com/ylikx/forpy/wiki/Working-with-arrays#changing-the-expected-storage-order

Since numpy can handle C and Fortran storage order, creating a transpose is very fast, since it involves only changing a few flags - using your example:

```python3
import numpy as np
from numpy import random

nrow = random.randint(2,6)
ncol = random.randint(2,6)
array = np.random.rand(ncol,nrow)
print(array.flags)
print("-----transpose------")
array = array.transpose()
print(array.flags)
```
